name: Nintendo Switch CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: git.libretro.com:5050/libretro-infrastructure/libretro-build-libnx-devkitpro:latest
      options: --user root

    steps:
    - uses: actions/checkout@v3

    - name: CMake
      run: |
          $DEVKITPRO/portlibs/switch/bin/aarch64-none-elf-cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_OPENGL=OFF -DENABLE_VULKAN=OFF -DENABLE_CUBEB=OFF -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON -G Ninja ${{ matrix.config.cmakeArgs }}
          cmake --build build --config Release

    - uses: actions/upload-artifact@v4
      with:
          name: duckstation-switch
          path: /__w/duckstation-switch/
