name: Nintendo Switch CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    
    steps:
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get -y install awscli ccache

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Mark git repository as safe
        run: git config --global --add safe.directory $PWD

      - uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-switch-${{ matrix.config.name }}-${{ github.sha }}
          restore-keys: ccache-switch-${{ matrix.config.name }}-

      - name: CMake
        run: |
          $DEVKITPRO/portlibs/switch/bin/aarch64-none-elf-cmake -Bbuild-release -DCMAKE_BUILD_TYPE=Release -DENABLE_OPENGL=OFF -DENABLE_VULKAN=OFF -DENABLE_CUBEB=OFF -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON
          cmake --build build-release
   
      - uses: actions/upload-artifact@v4
        with:
          name: duckstation-switch
          path: /__w/duckstation-switch/duckstation-switch/build-release/
